[package]
name = "penumbra-custody"
version = "0.63.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
decaf377-frost = { path = "../crypto/decaf377-frost" }
penumbra-proto = { path = "../proto" , features = ["rpc"] }
penumbra-keys = { path = "../core/keys" }
penumbra-transaction = { path = "../core/transaction" }

tokio = { version = "1.21.1", features = ["full"]}
anyhow = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "2.2", features = ["hex"] }
tracing = "0.1"
tonic = "0.10"
bytes = { version = "1", features = ["serde"] }
prost = "0.12"
futures = "0.3"
hex = "0.4"
rand_core = "0.6"
ed25519-consensus = "2.1"
base64 = "0.20"

[build-dependencies]
vergen = "5"

[dev-dependencies]
toml = "0.5"
